apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: servers.fortio.verf.io
spec:
  group: fortio.verf.io
  names:
    kind: Server
    listKind: ServerList
    plural: servers
    singular: server
  scope: Namespaced
  version: v1alpha1
  subresources:
    status: {}
