apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: curltests.fortio.verf.io
spec:
  group: fortio.verf.io
  names:
    kind: CurlTest
    listKind: CurlTestList
    plural: curltests
    singular: curltest
  scope: Namespaced
  version: v1alpha1
  subresources:
    status: {}
