apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: crontests.fortio.verf.io
spec:
  group: fortio.verf.io
  names:
    kind: CronTest
    listKind: CronTestList
    plural: crontests
    singular: crontest
  scope: Namespaced
  version: v1alpha1
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            schedule:
              type: string
              pattern: '^(\d+|\*)(/\d+)?(\s+(\d+|\*)(/\d+)?){4}$'
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: servers.fortio.verf.io
spec:
  group: fortio.verf.io
  names:
    kind: Server
    listKind: ServerList
    plural: servers
    singular: server
  scope: Namespaced
  version: v1alpha1
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            type:
              type: string
              pattern: '(LoadBalancer|NodePort)'
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: loadtests.fortio.verf.io
spec:
  group: fortio.verf.io
  names:
    kind: LoadTest
    listKind: LoadTestList
    plural: loadtests
    singular: loadtest
  scope: Namespaced
  version: v1alpha1
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        spec:
          required: ["url"]
          properties:
            url:
              type: string
              format: uri
            duration:
              type: string
              pattern: '\d+(s|m|h)'
            headers:
              type: array
              items:
                type: string
            user:
              type: string
            password:
              type: string
            qps:
              type: string
              pattern: '\d+'
            threads:
              type: string
              pattern: '\d+'
            method:
              type: string
              enum: GET,POST
            contentType:
              type: string
              pattern: '(.+):(.+)'
            payload:
              type: string
            payloadSize:
              type: string
              pattern: '\d+'
            maxPayloadSizeKB:
              type: string
              pattern: '\d+'
            payloadFile:
              type: string
            payloadConfigMap:
              type: string
            loglevel:
              type: string
              pattern: '(Debug|Verbose|Info|Warning|Error|Critical|Fatal)'
            order:
              type: string
              pattern: '\d+'
            stopOnFailure:
              type: string
              pattern: '(true|false)'
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: curltests.fortio.verf.io
spec:
  group: fortio.verf.io
  names:
    kind: CurlTest
    listKind: CurlTestList
    plural: curltests
    singular: curltest
  scope: Namespaced
  version: v1alpha1
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        spec:
          required: ["url", "lookForString"]
          properties:
            url:
              type: string
              format: uri
            lookForString:
              type: string
            headers:
              type: array
              items:
                type: string
            method:
              type: string
              pattern: '(GET|POST)'
            contentType:
              type: string
              pattern: '(.+):(.+)'
            payload:
              type: string
            payloadSize:
              type: string
              pattern: '\d+'
            maxPayloadSizeKB:
              type: string
              pattern: '\d+'
            payloadFile:
              type: string
            payloadConfigMap:
              type: string
            loglevel:
              type: string
              pattern: '(Debug|Verbose|Info|Warning|Error|Critical|Fatal)'
            order:
              type: string
              pattern: '\d+'
            stopOnFailure:
              type: string
              pattern: '(true|false)'
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: testruns.fortio.verf.io
spec:
  group: fortio.verf.io
  names:
    kind: TestRun
    listKind: TestRunList
    plural: testruns
    singular: testrun
  scope: Namespaced
  version: v1alpha1
  subresources:
    status: {}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fortio-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: fortio-operator
rules:
- apiGroups:
  - ""
  resources:
  - pods/log
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - '*'
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - '*'
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
- apiGroups:
  - fortio.verf.io
  resources:
  - '*'
  - curltests
  - servers
  verbs:
  - '*'
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fortio-operator
subjects:
- kind: ServiceAccount
  name: fortio-operator
roleRef:
  kind: Role
  name: fortio-operator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fortio-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: fortio-operator
  template:
    metadata:
      labels:
        name: fortio-operator
    spec:
      serviceAccountName: fortio-operator
      containers:
        - name: fortio-operator
          image: verfio/fortio-operator
          ports:
          - containerPort: 60000
            name: metrics
          - containerPort: 8082
            name: fortio-metrics
          command:
          - fortio-operator
          imagePullPolicy: Always
          readinessProbe:
            exec:
              command:
                - stat
                - /tmp/operator-sdk-ready
            initialDelaySeconds: 4
            periodSeconds: 10
            failureThreshold: 1
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "fortio-operator"
---
apiVersion: v1
kind: Service
metadata:
  name: fortio-metrics
  labels:
    app: fortio-metrics
spec:
  ports:
  - name: http
    port: 8082
    targetPort: 8082
  type: LoadBalancer
  selector:
    name: fortio-operator
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fortio-data-dir
  namespace: default
